### PR TITLE
75 OpenShift

### PR DESCRIPTION
**Pull request by jschaefer311**
Hey Ashely, let's see if you get this one... @ahardin-rh

All approved diagrams are now ready for doc upload. This includes:
image
image
image
image
image

### CODE REVIEW

**Comment by wesruv** [comment]
@jschaefer311 aha! This was setup as private initially, should work now!

**Comment by jschaefer311** [comment]
@wesruv sweet, thanks! I'll get her to check it out again.

**Comment by ahardin-rh** [comment]
@jschaefer311 @wesruv Thank you both! I can access the files now.

**Comment by jschaefer311** [comment]
Yay, success! @ahardin-rh

**Comment by wesruv** [comment]
So if this is approved and the work is done (at least for now) I'd recommend "Merging" the pull request so the work is in the master branch :smile:

If it turns out you're more comfortable doing back and forth and approval in another system (JIRA, email, etc) then there's no need for Pull Requests and we can work out a different Git workflow.

**Comment by ahardin-rh** [comment]
@jschaefer311 I applied the files to OpenShift docs.
4.5: https://github.com/openshift/openshift-docs/pull/23076
4.4: https://github.com/openshift/openshift-docs/pull/23081
4.3: https://github.com/openshift/openshift-docs/pull/23083

**Comment by jschaefer311** [comment]
Oh, awesome! :) So do I still need to merge the pull request or did you do that already, Ashley?

**Comment by ahardin-rh** [comment]
@jschaefer311 I think you can merge the PR for your needs. I just copied the files from here manually into those new doc PRs. Let me know if I missed anything with the process. Thanks!

**Pull request merged**
